/**
 * Bakes SVG path data for "YES" and "NO" from Phantom-Bold.woff2 into a TS
 * constants file at lib/yesno-paths.ts.
 *
 * The component imports those constants and feeds them to flubber for a
 * goo-style shape morph between the two words.
 *
 * Run: bun run scripts/bake-yesno.ts
 */
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import opentype from "opentype.js";
import wawoff2 from "wawoff2";

const FONT_SIZE = 220;

async function bake() {
  const woff2 = await readFile(
    resolve(process.cwd(), "public/fonts/Phantom-Bold.woff2")
  );
  const ttf: Uint8Array = await wawoff2.decompress(woff2);
  // opentype expects an ArrayBuffer
  const buf = ttf.buffer.slice(ttf.byteOffset, ttf.byteOffset + ttf.byteLength);
  const font = opentype.parse(buf);

  // Each shape is RE-RENDERED at an offset that centers its own bbox at (0,0).
  // That way the SVG <path> stays visually pinned to the same anchor as it
  // morphs between shapes — no drift, no lopsided framing.
  const make = (text: string) => {
    const probe = font.getPath(text, 0, 0, FONT_SIZE);
    const b = probe.getBoundingBox();
    const cx = (b.x1 + b.x2) / 2;
    const cy = (b.y1 + b.y2) / 2;
    const centered = font.getPath(text, -cx, -cy, FONT_SIZE);
    const cb = centered.getBoundingBox();
    return {
      d: centered.toPathData(2),
      x1: cb.x1,
      y1: cb.y1,
      x2: cb.x2,
      y2: cb.y2,
    };
  };

  const yes = make("YES");
  const no = make("NO");
  // No idle/blob shape: at rest the morph is fully transparent (opacity 0).
  // At rest the shape value sits at the YES↔NO midpoint but is invisible,
  // and as the card drags either direction the opacity rises and the shape
  // resolves to YES (right) or NO (left).

  const bbox = (s: { x1: number; y1: number; x2: number; y2: number }) => ({
    x1: s.x1,
    y1: s.y1,
    x2: s.x2,
    y2: s.y2,
  });

  const out = `// AUTO-GENERATED by scripts/bake-yesno.ts — do not edit by hand.
// Source: public/fonts/Phantom-Bold.woff2 at fontSize ${FONT_SIZE}.
// Each path is re-rendered with a -cx,-cy offset so its bbox is centered
// at the origin, so flubber morphs between shapes that share an anchor.

export const YES_PATH = ${JSON.stringify(yes.d)};
export const NO_PATH = ${JSON.stringify(no.d)};

export const YES_BBOX = ${JSON.stringify(bbox(yes))};
export const NO_BBOX = ${JSON.stringify(bbox(no))};
`;

  await writeFile(resolve(process.cwd(), "lib/yesno-paths.ts"), out);
  console.log("baked", {
    yes: yes.d.length,
    no: no.d.length,
  });
}

bake().catch((e) => {
  console.error(e);
  process.exit(1);
});
