#!/usr/bin/env python3
"""Package VIMA demo media/artifacts into a shareable zip.

Default output intentionally excludes raw input videos so the archive stays small.
Use --include-raw if you want to include data/video01.mp4 too.
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

ROOT = Path(__file__).resolve().parents[1]

DEFAULT_INCLUDE_PATHS = [
    Path("demo"),
    Path("proof"),
    Path("dashboard/assets"),
    Path("dashboard/data"),
    Path("paper/main.pdf"),
    Path("paper/figures"),
    Path("artifacts/vima_test_share/previews"),
    Path("artifacts/vima_test_share/depth"),
    Path("artifacts/vima_test_share/masks"),
    Path("artifacts/vima_test_share/memory"),
    Path("artifacts/vima_test_share/manifest.json"),
]

RAW_PATHS = [
    Path("data/video01.mp4"),
]

INCLUDE_EXTS = {
    ".css",
    ".html",
    ".jpg",
    ".jpeg",
    ".js",
    ".json",
    ".md",
    ".mov",
    ".mp4",
    ".pdf",
    ".png",
    ".txt",
    ".webp",
}

SKIP_DIRS = {
    ".git",
    ".next",
    ".venv",
    "__pycache__",
    "node_modules",
}

SKIP_NAMES = {
    ".DS_Store",
}


def should_include(path: Path) -> bool:
    if path.name in SKIP_NAMES:
        return False
    if any(part in SKIP_DIRS for part in path.parts):
        return False
    return path.is_file() and path.suffix.lower() in INCLUDE_EXTS


def iter_files(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    seen: set[Path] = set()
    for rel in paths:
        abs_path = ROOT / rel
        if not abs_path.exists():
            continue
        candidates = [abs_path] if abs_path.is_file() else abs_path.rglob("*")
        for candidate in candidates:
            if not should_include(candidate):
                continue
            resolved = candidate.resolve()
            if resolved in seen:
                continue
            seen.add(resolved)
            files.append(candidate)
    return sorted(files, key=lambda p: p.relative_to(ROOT).as_posix())


def format_size(num_bytes: int) -> str:
    units = ["B", "KB", "MB", "GB"]
    size = float(num_bytes)
    for unit in units:
        if size < 1024 or unit == units[-1]:
            return f"{size:.1f} {unit}" if unit != "B" else f"{int(size)} B"
        size /= 1024
    return f"{num_bytes} B"


def build_manifest(files: list[Path]) -> str:
    lines = [
        "VIMA demo media archive",
        "",
        "Contents:",
    ]
    for file in files:
        rel = file.relative_to(ROOT).as_posix()
        lines.append(f"- {rel} ({format_size(file.stat().st_size)})")
    lines.append("")
    lines.append("Generated by scripts/package_demo_assets.py")
    return "\n".join(lines)


def package(out_path: Path, include_raw: bool, dry_run: bool) -> int:
    include_paths = list(DEFAULT_INCLUDE_PATHS)
    if include_raw:
        include_paths.extend(RAW_PATHS)

    files = iter_files(include_paths)
    if not files:
        raise SystemExit("No demo assets found to package.")

    out_abs = (ROOT / out_path).resolve() if not out_path.is_absolute() else out_path.resolve()
    out_abs.parent.mkdir(parents=True, exist_ok=True)

    total_input = sum(file.stat().st_size for file in files)
    print(f"[vima] packaging {len(files)} files ({format_size(total_input)})")
    for file in files:
        print(f"  + {file.relative_to(ROOT).as_posix()}")

    if dry_run:
        print("[vima] dry run only; no zip written")
        return 0

    with ZipFile(out_abs, "w", compression=ZIP_DEFLATED) as zf:
        for file in files:
            zf.write(file, file.relative_to(ROOT).as_posix())
        zf.writestr("MANIFEST.txt", build_manifest(files))

    print(f"[vima] wrote {out_abs} ({format_size(out_abs.stat().st_size)})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Package VIMA demo media into a shareable zip.")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("artifacts/vima_demo_media.zip"),
        help="Output zip path. Defaults to artifacts/vima_demo_media.zip.",
    )
    parser.add_argument(
        "--include-raw",
        action="store_true",
        help="Include raw input videos under data/. Off by default to keep the archive small.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print files without writing the zip.")
    args = parser.parse_args()
    return package(args.out, args.include_raw, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
